'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { BookOpenCheck, Brain, CheckCircle2, Download, FileText, Image as ImageIcon, Plus, Search, Upload, X } from 'lucide-react';
import { toast } from 'sonner';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';

const bloomLevels = ['Remember', 'Understand', 'Apply', 'Analyse', 'Evaluate', 'Create'] as const;
const questionTypes = ['True or False', 'Multiple choice', 'Fill in the blank', 'Matching', 'Short answer', 'Long answer / Essay', 'Scenario based', 'Photo based', 'Practical task'] as const;
type BloomLevel = typeof bloomLevels[number]; type QuestionType = typeof questionTypes[number];
type Question = { id: string; text: string; answer: string; type: QuestionType; bloom: BloomLevel; marks: number; module: string; difficulty: string; imageName?: string };
const bloomHelp: Record<BloomLevel, string> = { Remember: 'Recall facts, terms and concepts.', Understand: 'Explain ideas or interpret information.', Apply: 'Use knowledge in a familiar situation.', Analyse: 'Identify parts and relationships.', Evaluate: 'Justify a decision using evidence.', Create: 'Design or produce an original solution.' };
function escapeHtml(value: string) { return value.replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[c]!); }

export function QuestionBankManager() {
  const [questions, setQuestions] = useState<Question[]>([]); const [showForm, setShowForm] = useState(false); const [search, setSearch] = useState(''); const [bloomFilter, setBloomFilter] = useState('All'); const [typeFilter, setTypeFilter] = useState('All'); const [templateReady, setTemplateReady] = useState(false);
  const [importedFiles, setImportedFiles] = useState<{ name: string; size: number; importedAt: string }[]>([]);
  const [text, setText] = useState(''); const [answer, setAnswer] = useState(''); const [type, setType] = useState<QuestionType>('Multiple choice'); const [bloom, setBloom] = useState<BloomLevel | ''>(''); const [marks, setMarks] = useState(1); const [module, setModule] = useState(''); const [difficulty, setDifficulty] = useState('Medium'); const [imageName, setImageName] = useState(''); const importRef = useRef<HTMLInputElement>(null);
  useEffect(() => { try { const saved = localStorage.getItem('teacher-question-bank'); if (saved) setQuestions(JSON.parse(saved)); } catch {} }, []);
  useEffect(() => { localStorage.setItem('teacher-question-bank', JSON.stringify(questions)); }, [questions]);
  const filtered = useMemo(() => questions.filter((q) => (bloomFilter === 'All' || q.bloom === bloomFilter) && (typeFilter === 'All' || q.type === typeFilter) && `${q.text} ${q.module}`.toLowerCase().includes(search.toLowerCase())), [questions, search, bloomFilter, typeFilter]);
  function saveQuestion() { if (!text.trim() || !answer.trim() || !module.trim() || !bloom) { toast.error('Question, expected answer, module and Bloom’s level are required.'); return; } if (type === 'Photo based' && !imageName) { toast.error('Attach an image for a photo-based question.'); return; } setQuestions((old) => [{ id: crypto.randomUUID(), text: text.trim(), answer: answer.trim(), type, bloom, marks, module: module.trim(), difficulty, imageName: imageName || undefined }, ...old]); setText(''); setAnswer(''); setBloom(''); setMarks(1); setModule(''); setImageName(''); setShowForm(false); toast.success('Question added to the bank.'); }
  function downloadTemplate() { const content = `<html><head><meta charset="utf-8"><style>body{font-family:Arial;margin:42px}h1{color:#123b70}table{border-collapse:collapse;width:100%}td,th{border:1px solid #777;padding:8px}</style></head><body><h1>G.S BTR RWAMIKO TSS — Question Import Template</h1><p>Complete every field. Do not rename headings. Repeat this table for every question.</p><table><tr><th>Module code/name</th><td>[Required]</td></tr><tr><th>Question type</th><td>True or False | Multiple choice | Fill in the blank | Matching | Short answer | Long answer / Essay | Scenario based | Photo based | Practical task</td></tr><tr><th>Bloom's taxonomy level</th><td>Remember | Understand | Apply | Analyse | Evaluate | Create</td></tr><tr><th>Difficulty</th><td>Easy | Medium | Challenging</td></tr><tr><th>Marks</th><td>[Number]</td></tr><tr><th>Question</th><td>[Required]</td></tr><tr><th>Options / matching pairs</th><td>[If applicable]</td></tr><tr><th>Expected answer / marking guide</th><td>[Required]</td></tr><tr><th>Image reference</th><td>[Photo-based questions only]</td></tr></table></body></html>`; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type: 'application/msword' })); link.download = 'BTR-Rwamiko-Question-Bank-Template.doc'; link.click(); URL.revokeObjectURL(link.href); setTemplateReady(true); toast.success('Word template downloaded.'); }
  function importDocument(file?: File) { if (!file) return; if (!templateReady) { toast.error('Download the official template before uploading questions.'); if (importRef.current) importRef.current.value = ''; return; } if (!/\.(pdf|doc|docx)$/i.test(file.name)) { toast.error('Upload a PDF, DOC or DOCX file.'); return; } if (file.size > 15 * 1024 * 1024) { toast.error('The document must not exceed 15 MB.'); return; } setImportedFiles((old) => [{ name: file.name, size: file.size, importedAt: new Date().toLocaleString() }, ...old]); toast.success(`${file.name} uploaded for academic review.`); }
  function downloadBank() { if (!filtered.length) { toast.error('There are no questions in the selected view.'); return; } const rows = filtered.map((q, i) => `<section><div class="meta">${escapeHtml(q.module)} • ${escapeHtml(q.type)} • Bloom: ${escapeHtml(q.bloom)} • ${q.marks} mark(s)</div><h3>${i + 1}. ${escapeHtml(q.text)}</h3>${q.imageName ? `<p>[Image: ${escapeHtml(q.imageName)}]</p>` : ''}<div class="answer"><b>Marking guide:</b> ${escapeHtml(q.answer)}</div></section>`).join(''); const html = `<html><head><title>Question Bank</title><style>@page{size:A4;margin:22mm}body{font-family:Arial;color:#172033}header{display:flex;align-items:center;border-bottom:3px solid #123b70}header img{width:105px;margin-right:18px}.watermark{position:fixed;inset:30% 0;text-align:center;font-size:60px;font-weight:bold;color:rgba(18,59,112,.08);transform:rotate(-32deg);z-index:-1}section{margin:24px 0;page-break-inside:avoid}.meta{font-size:11px;color:#52647c}.answer{padding:10px;background:#f1f5f9;font-size:13px}</style></head><body><div class="watermark">G.S BTR RWAMIKO TSS</div><header><img src="${location.origin}/school-logo.png"><div><h1>G.S BTR RWAMIKO TSS</h1><p>Official Question Bank • ${new Date().toLocaleDateString()}</p></div></header>${rows}<script>window.onload=()=>window.print()</script></body></html>`; const win = window.open('', '_blank'); if (!win) { toast.error('Allow pop-ups to download the question bank.'); return; } win.document.write(html); win.document.close(); }
  return <div className="space-y-6"><section className="rounded-3xl bg-gradient-to-r from-slate-950 via-blue-950 to-indigo-900 p-6 text-white sm:p-8"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div className="flex gap-4"><div className="h-fit rounded-2xl bg-cyan-400/15 p-3 text-cyan-300"><Brain className="size-8" /></div><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Assessment intelligence</p><h2 className="text-2xl font-bold">Professional Question Bank</h2><p className="mt-2 max-w-2xl text-sm text-slate-300">Create balanced assessments with compulsory Bloom’s taxonomy, structured formats and marking guides.</p></div></div><Button onClick={() => setShowForm(true)} className="bg-cyan-400 text-slate-950 hover:bg-cyan-300"><Plus /> Create question</Button></div></section>
  <div className="grid gap-4 sm:grid-cols-3">{[['Total questions', questions.length], ['Bloom coverage', `${new Set(questions.map(q => q.bloom)).size} / 6`], ['Question formats', `${new Set(questions.map(q => q.type)).size} / ${questionTypes.length}`]].map(([label, value]) => <Card key={label}><CardContent className="p-5"><p className="text-xs uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></CardContent></Card>)}</div>
  <Card className="border-blue-200"><CardContent className="p-6"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div><h3 className="flex items-center gap-2 font-bold"><FileText className="size-5 text-blue-700" /> Import prepared question papers</h3><p className="mt-1 text-sm text-muted-foreground">Download the official template, then upload Word or PDF (maximum 15 MB). Document contents are not translated.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={downloadTemplate}><Download /> Download Word template</Button><input ref={importRef} type="file" accept=".pdf,.doc,.docx" className="hidden" onChange={e => importDocument(e.target.files?.[0])} data-no-translate /><Button onClick={() => importRef.current?.click()} disabled={!templateReady}><Upload /> Upload completed file</Button></div></div>{templateReady && <p className="mt-4 flex items-center gap-2 text-xs font-medium text-emerald-700"><CheckCircle2 className="size-4" /> Template downloaded — upload enabled.</p>}{importedFiles.length > 0 && <div className="mt-4 space-y-2" data-no-translate>{importedFiles.map((file) => <div key={`${file.name}-${file.importedAt}`} className="flex items-center gap-3 rounded-lg border bg-white p-3 text-sm"><FileText className="size-4 text-blue-700" /><span className="min-w-0 flex-1 truncate font-medium">{file.name}</span><span className="text-xs text-muted-foreground">{(file.size / 1024 / 1024).toFixed(2)} MB • {file.importedAt}</span><Badge variant="warning">Pending review</Badge></div>)}</div>}</CardContent></Card>
  {showForm && <Card className="border-cyan-300"><CardContent className="p-6"><div className="mb-5 flex justify-between"><div><h3 className="text-lg font-bold">Create a bank question</h3><p className="text-sm text-muted-foreground">All academic classification fields are required.</p></div><Button variant="ghost" size="icon" onClick={() => setShowForm(false)}><X /></Button></div><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Question type *<select className="mt-2 h-10 w-full rounded-md border bg-white px-3" value={type} onChange={e => setType(e.target.value as QuestionType)}>{questionTypes.map(x => <option key={x}>{x}</option>)}</select></label><label className="text-sm font-medium">Bloom’s taxonomy level *<select className="mt-2 h-10 w-full rounded-md border bg-white px-3" value={bloom} onChange={e => setBloom(e.target.value as BloomLevel)}><option value="">Select cognitive level</option>{bloomLevels.map(x => <option key={x}>{x} — {bloomHelp[x]}</option>)}</select></label><label className="text-sm font-medium">Module / subject *<Input className="mt-2" value={module} onChange={e => setModule(e.target.value)} placeholder="Example: NIT — Computer Networks" /></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Difficulty *<select className="mt-2 h-10 w-full rounded-md border bg-white px-3" value={difficulty} onChange={e => setDifficulty(e.target.value)}><option>Easy</option><option>Medium</option><option>Challenging</option></select></label><label className="text-sm font-medium">Marks *<Input className="mt-2" type="number" min={1} value={marks} onChange={e => setMarks(Number(e.target.value))} /></label></div><label className="text-sm font-medium md:col-span-2">Question *<textarea className="mt-2 min-h-28 w-full rounded-md border p-3" value={text} onChange={e => setText(e.target.value)} /></label><label className="text-sm font-medium md:col-span-2">Expected answer / marking guide *<textarea className="mt-2 min-h-24 w-full rounded-md border p-3" value={answer} onChange={e => setAnswer(e.target.value)} /></label>{type === 'Photo based' && <label className="text-sm font-medium md:col-span-2">Question image *<Input className="mt-2" type="file" accept="image/jpeg,image/png,image/webp" onChange={e => setImageName(e.target.files?.[0]?.name ?? '')} data-no-translate /></label>}</div><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" onClick={() => setShowForm(false)}>Cancel</Button><Button onClick={saveQuestion}><BookOpenCheck /> Add to question bank</Button></div></CardContent></Card>}
  <Card><CardContent className="p-6"><div className="mb-5 flex flex-col gap-3 xl:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input className="pl-9" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search question text or module" /></div><select className="h-10 rounded-md border bg-white px-3" value={bloomFilter} onChange={e => setBloomFilter(e.target.value)}><option>All</option>{bloomLevels.map(x => <option key={x}>{x}</option>)}</select><select className="h-10 rounded-md border bg-white px-3" value={typeFilter} onChange={e => setTypeFilter(e.target.value)}><option>All</option>{questionTypes.map(x => <option key={x}>{x}</option>)}</select><Button onClick={downloadBank}><Download /> Download watermarked bank</Button></div><div className="space-y-3">{filtered.map(q => <article key={q.id} className="rounded-2xl border p-5"><div className="flex flex-wrap gap-2"><Badge>{q.bloom}</Badge><Badge variant="outline">{q.type}</Badge><Badge variant="secondary">{q.difficulty}</Badge><b className="ml-auto text-sm">{q.marks} mark{q.marks === 1 ? '' : 's'}</b></div><p className="mt-4 font-semibold">{q.text}</p><div className="mt-3 rounded-lg bg-emerald-50 p-3 text-sm"><b>Expected answer:</b> {q.answer}</div><div className="mt-3 flex gap-3 text-xs text-muted-foreground"><span data-no-translate>{q.module}</span>{q.imageName && <span className="flex gap-1" data-no-translate><ImageIcon className="size-3" />{q.imageName}</span>}</div></article>)}{!filtered.length && <div className="rounded-xl border border-dashed p-12 text-center"><Brain className="mx-auto mb-3 size-9 text-slate-300" /><p className="font-medium">No questions in this view</p></div>}</div></CardContent></Card></div>;
}
