import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, BriefcaseBusiness, GraduationCap, Wrench } from 'lucide-react';
import { PublicHeader } from '@/components/public/public-header';
import { PublicFooter } from '@/components/public/public-footer';
import { programmes } from '@/lib/programmes';

export const metadata = { title: 'Programmes | G.S BTR Rwamiko TSS', description: 'Explore technical and professional study pathways at G.S BTR Rwamiko TSS.' };

export default function ProgrammesPage() {
  return <main className="min-h-screen bg-[#f4f8f8] text-slate-950"><PublicHeader />
    <section className="relative overflow-hidden bg-slate-950 px-5 py-24 text-white sm:px-8 lg:py-32"><div className="school-grid absolute inset-0 opacity-15" /><div className="absolute -right-32 -top-32 size-[32rem] rounded-full bg-cyan-400/15 blur-3xl" /><div className="relative mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[0.25em] text-cyan-300">Choose a future you can build</p><h1 className="mt-5 max-w-4xl text-5xl font-black tracking-[-0.05em] sm:text-7xl">Seven pathways. One strong foundation.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-300">Discover what each programme teaches, the practical work you will complete, and the careers or further studies it can open. Choose with knowledge—not guesswork.</p><div className="mt-10 flex flex-wrap gap-6 text-sm text-slate-300"><span className="flex items-center gap-2"><Wrench className="size-5 text-cyan-300" />Practice-led learning</span><span className="flex items-center gap-2"><BriefcaseBusiness className="size-5 text-cyan-300" />Career preparation</span><span className="flex items-center gap-2"><GraduationCap className="size-5 text-cyan-300" />Further-study pathways</span></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="mb-12 max-w-2xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-700">Explore our programmes</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Find the work that inspires you.</h2></div><div className="grid gap-7 md:grid-cols-2 xl:grid-cols-3">{programmes.map((programme, index) => <Link key={programme.slug} href={`/programmes/${programme.slug}`} className={`group overflow-hidden rounded-[1.75rem] border border-slate-200 bg-white shadow-sm transition duration-300 hover:-translate-y-2 hover:shadow-2xl ${index === programmes.length - 1 ? 'md:col-span-2 xl:col-span-1' : ''}`}><div className="relative aspect-[16/10] overflow-hidden"><Image src={programme.image} alt={`${programme.name} practical learning`} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 33vw" /><div className={`absolute inset-0 bg-linear-to-t ${programme.accent} opacity-35`} /><span className="absolute left-5 top-5 rounded-full bg-slate-950/75 px-3 py-1 text-xs font-black tracking-widest text-white backdrop-blur">{programme.code}</span></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-widest text-cyan-700">{programme.levels.join(' • ')}</p><h3 className="mt-3 text-2xl font-black tracking-tight">{programme.name}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{programme.shortDescription}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-black text-slate-950">Explore this programme <ArrowRight className="size-4 transition group-hover:translate-x-1" /></span></div></Link>)}</div></section>
    <section className="bg-cyan-400 px-5 py-16 text-center sm:px-8"><h2 className="text-3xl font-black tracking-tight sm:text-4xl">Ready to turn interest into ability?</h2><p className="mx-auto mt-4 max-w-2xl text-slate-800">Review the programme that fits your goals, then begin your admission application.</p><Link href="/admissions" className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-full bg-slate-950 px-7 font-bold text-white hover:bg-slate-800">Apply for admission <ArrowRight className="size-4" /></Link></section><PublicFooter /></main>;
}
