import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Award, BookOpenCheck, HeartHandshake, ShieldCheck, Sparkles, UsersRound } from 'lucide-react';
import { PublicHeader } from '@/components/public/public-header';
import { PublicFooter } from '@/components/public/public-footer';

export const metadata = { title: 'Our Story | G.S BTR Rwamiko TSS', description: 'Discover the learning culture, values, teachers, and legacy of G.S BTR Rwamiko TSS.' };

const values = [
  { icon: BookOpenCheck, title: 'Knowledge with purpose', text: 'Academic understanding is connected to practical application, reflection, and service.' },
  { icon: ShieldCheck, title: 'Discipline and integrity', text: 'Learners are guided to work safely, act honestly, respect others, and take responsibility.' },
  { icon: HeartHandshake, title: 'Community', text: 'Teachers, families, learners, and partners contribute to a school culture where progress is shared.' },
  { icon: Sparkles, title: 'Ambition', text: 'Every learner is encouraged to improve, solve problems, and imagine a meaningful future.' },
];

export default function OurStoryPage() {
  return <main className="min-h-screen bg-[#f7faf9] text-slate-950"><PublicHeader />
    <section className="relative isolate min-h-[620px] overflow-hidden bg-slate-950"><Image src="/students-campus.png" alt="Students together on the G.S BTR Rwamiko TSS campus" fill priority className="object-cover object-center" /><div className="absolute inset-0 bg-linear-to-r from-slate-950 via-slate-950/75 to-slate-950/15" /><div className="relative mx-auto flex min-h-[620px] max-w-7xl items-end px-5 pb-20 pt-24 text-white sm:px-8 lg:pb-28"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.25em] text-cyan-300">Our story</p><h1 className="mt-5 text-5xl font-black leading-[.95] tracking-[-0.05em] sm:text-7xl">Rooted in community. Ready for the future.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-200">G.S BTR Rwamiko TSS is a learning community where academic effort, technical competence, character, and opportunity grow together.</p></div></div></section>
    <section className="mx-auto grid max-w-7xl gap-14 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:items-center lg:py-28"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-700">A culture of progress</p><h2 className="mt-4 text-4xl font-black tracking-[-0.04em] sm:text-5xl">A school is more than its buildings.</h2><p className="mt-6 text-lg leading-8 text-slate-600">It is the daily habit of arriving prepared, asking better questions, practising until a skill becomes dependable, supporting classmates, and accepting guidance. That culture shapes both capable graduates and responsible citizens.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{values.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className="size-6 text-cyan-700" /><h3 className="mt-4 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div><div className="grid grid-cols-2 gap-4"><Image src="/students-classroom.png" alt="Learners collaborating in class" width={800} height={1000} className="h-full min-h-80 rounded-[2rem] object-cover" /><div className="grid gap-4"><Image src="/images/programmes/construction-electrical-workshop.png" alt="Technical learners in supervised practical work" width={800} height={520} className="h-full rounded-[2rem] object-cover" /><Image src="/images/programmes/accounting-class.png" alt="Students learning with an experienced teacher" width={800} height={520} className="h-full rounded-[2rem] object-cover" /></div></div></section>
    <section className="bg-slate-950 px-5 py-20 text-white sm:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-300">A legacy earned through work</p><h2 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">Performance, practice, and professional confidence.</h2><p className="mt-6 text-lg leading-8 text-slate-300">The school is proud of its tradition of strong performance and graduates succeeding in both practical and written national assessments. That achievement grows from experienced teachers, structured preparation, repeated practice, and learners who take improvement seriously.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3"><StoryPoint icon={Award} title="Achievement" text="Preparation values mastery—not memorisation alone—across practical and written assessment." /><StoryPoint icon={UsersRound} title="Experienced guidance" text="Teachers combine subject knowledge, classroom care, demonstration, feedback, and professional expectations." /><StoryPoint icon={HeartHandshake} title="Whole-person growth" text="Sport, leadership, faith, service, creativity, and friendship help learners grow beyond examination results." /></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="relative overflow-hidden rounded-[2.5rem] bg-cyan-400 p-8 sm:p-14"><div className="relative z-10 max-w-2xl"><p className="text-xs font-black uppercase tracking-widest">Become part of the next chapter</p><h2 className="mt-4 text-4xl font-black tracking-tight">Bring your curiosity. Build your capability.</h2><p className="mt-5 leading-7 text-slate-800">Explore our programmes and choose a pathway aligned with the future you want to create.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/programmes" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-slate-950 px-6 font-bold text-white">Explore programmes <ArrowRight className="size-4" /></Link><Link href="/admissions" className="inline-flex min-h-12 items-center rounded-full border border-slate-950/25 px-6 font-bold">Apply for admission</Link></div></div></div></section><PublicFooter /></main>;
}

function StoryPoint({ icon: Icon, title, text }: { icon: typeof Award; title: string; text: string }) { return <article className="rounded-3xl border border-white/10 bg-white/5 p-7"><Icon className="size-7 text-cyan-300" /><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-3 leading-7 text-slate-300">{text}</p></article>; }
