import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Church, Dumbbell, Heart, Lightbulb, Music2, Trophy, UsersRound } from 'lucide-react';
import { PublicHeader } from '@/components/public/public-header';
import { PublicFooter } from '@/components/public/public-footer';

export const metadata = { title: 'Student Life | G.S BTR Rwamiko TSS', description: 'Explore learning, sport, clubs, faith, friendship, and leadership in student life.' };

const experiences = [
  { icon: Trophy, title: 'Sport and teamwork', text: 'Training, friendly competition, fitness, resilience, and respect teach learners to win and grow together.' },
  { icon: Lightbulb, title: 'Clubs and innovation', text: 'Technical, entrepreneurship, debate, environment, and creative activities turn interests into initiative.' },
  { icon: Church, title: 'Faith and reflection', text: 'Prayer, worship, and values-based reflection support gratitude, compassion, discipline, and hope.' },
  { icon: Music2, title: 'Culture and creativity', text: 'Music, dance, performance, and celebration give students confidence and strengthen belonging.' },
  { icon: UsersRound, title: 'Leadership and service', text: 'Student responsibility and community service develop communication, reliability, and care for others.' },
  { icon: Heart, title: 'Friendship and wellbeing', text: 'Shared study, play, mentoring, and pastoral support help every learner feel known and encouraged.' },
];

export default function StudentLifePage() {
  return <main className="min-h-screen bg-[#f6faf9] text-slate-950"><PublicHeader />
    <section className="relative overflow-hidden bg-slate-950 px-5 pb-20 pt-20 text-white sm:px-8 lg:pb-28 lg:pt-28"><div className="absolute -left-40 top-0 size-[34rem] rounded-full bg-cyan-400/20 blur-3xl" /><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[0.25em] text-cyan-300">Student life</p><h1 className="mt-5 text-5xl font-black leading-[.95] tracking-[-0.05em] sm:text-7xl">Learn fully. Live meaningfully.</h1><p className="mt-7 text-lg leading-8 text-slate-300">School life develops the whole person: mind, hands, health, character, faith, creativity, friendship, and leadership.</p></div><div className="grid grid-cols-2 gap-4"><Image src="/students-campus.png" alt="Students sharing school life on campus" width={1000} height={1200} className="col-span-2 aspect-[16/8] w-full rounded-[2rem] object-cover" priority /><Image src="/students-classroom.png" alt="Students collaborating in class" width={700} height={700} className="aspect-square w-full rounded-[2rem] object-cover" /><Image src="/students-workshop.png" alt="Students sharing practical learning" width={700} height={700} className="aspect-square w-full rounded-[2rem] object-cover" /></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-700">Beyond the timetable</p><h2 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">Space to belong, contribute, and discover.</h2><p className="mt-6 text-lg leading-8 text-slate-600">Lessons matter, but so do the experiences between them. Activities help learners recognise strengths, build healthy routines, practise responsibility, and form friendships that make school memorable.</p></div><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{experiences.map(({ icon: Icon, title, text }, index) => <article key={title} className={`rounded-[1.75rem] p-7 ${index % 2 ? 'bg-slate-950 text-white' : 'border border-slate-200 bg-white'}`}><span className={`grid size-12 place-items-center rounded-2xl ${index % 2 ? 'bg-cyan-400 text-slate-950' : 'bg-cyan-100 text-cyan-800'}`}><Icon className="size-6" /></span><h3 className="mt-5 text-xl font-black">{title}</h3><p className={`mt-3 leading-7 ${index % 2 ? 'text-slate-300' : 'text-slate-600'}`}>{text}</p></article>)}</div></section>
    <section className="overflow-hidden bg-cyan-400"><div className="mx-auto grid max-w-7xl lg:grid-cols-2"><div className="relative min-h-[420px]"><Image src="/images/programmes/network-electronics-lab.png" alt="Students collaborating during practical learning" fill className="object-cover" sizes="(max-width: 1024px) 100vw, 50vw" /></div><div className="flex items-center p-8 sm:p-14 lg:p-16"><div><Dumbbell className="size-8" /><p className="mt-6 text-xs font-black uppercase tracking-[0.2em]">A balanced week</p><h2 className="mt-4 text-4xl font-black tracking-tight">Study hard. Practise safely. Play fairly. Rest well.</h2><p className="mt-6 leading-8 text-slate-800">A healthy rhythm helps learners sustain concentration and confidence. Academic study, workshop practice, movement, social time, prayer, and rest each contribute to long-term success.</p></div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 text-center sm:px-8 lg:py-28"><h2 className="text-4xl font-black tracking-tight sm:text-5xl">See yourself here.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-600">Choose a programme, prepare your application, and join a community that expects you to learn, participate, and grow.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/programmes" className="inline-flex min-h-12 items-center gap-2 rounded-full border border-slate-300 bg-white px-6 font-bold">Explore programmes</Link><Link href="/admissions" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-slate-950 px-6 font-bold text-white">Apply for admission <ArrowRight className="size-4" /></Link></div></section><PublicFooter /></main>;
}
