import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowRight, BookOpenCheck, BriefcaseBusiness, CheckCircle2, GraduationCap, Hammer } from 'lucide-react';
import { ProgrammeGallery } from '@/components/public/programme-gallery';
import { PublicHeader } from '@/components/public/public-header';
import { PublicFooter } from '@/components/public/public-footer';
import { findProgramme, programmes } from '@/lib/programmes';

export function generateStaticParams() { return programmes.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const programme = findProgramme((await params).slug); return programme ? { title: `${programme.name} | G.S BTR Rwamiko TSS`, description: programme.shortDescription } : {}; }

export default async function ProgrammeDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const programme = findProgramme((await params).slug); if (!programme) notFound();
  const nextProgramme = programmes[(programmes.findIndex((item) => item.slug === programme.slug) + 1) % programmes.length];
  return <main className="min-h-screen bg-[#f5f8f8] text-slate-950"><PublicHeader />
    <section className={`relative overflow-hidden bg-linear-to-br ${programme.accent} px-5 py-20 text-white sm:px-8 lg:py-28`}><div className="school-grid absolute inset-0 opacity-15" /><div className="relative mx-auto max-w-7xl"><Link href="/programmes" className="inline-flex items-center gap-2 text-sm font-bold text-white/80 hover:text-white"><ArrowLeft className="size-4" />All programmes</Link><div className="mt-10 grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><span className="rounded-full border border-white/30 bg-white/10 px-4 py-2 text-xs font-black tracking-[0.2em] backdrop-blur">{programme.code} • {programme.levels.join(' • ')}</span><h1 className="mt-7 text-5xl font-black leading-none tracking-[-0.05em] sm:text-7xl">{programme.name}</h1><p className="mt-6 text-lg leading-8 text-white/85">{programme.shortDescription}</p></div><ProgrammeGallery images={programme.gallery} /></div></div></section>
    <section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:py-28"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-700">What this programme means</p><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-5xl">Learn the system. Practise the craft. Solve real problems.</h2><p className="mt-6 text-lg leading-8 text-slate-600">{programme.overview}</p><div className="mt-9 rounded-3xl bg-slate-950 p-7 text-white"><BookOpenCheck className="size-7 text-cyan-300" /><h3 className="mt-4 text-xl font-black">How learning happens</h3><p className="mt-3 leading-7 text-slate-300">Theory builds understanding; demonstrations show correct methods; guided practice builds confidence; and projects ask learners to apply skills independently, safely, and professionally.</p></div></div><InfoList icon={CheckCircle2} title="Competencies you develop" items={programme.skills} /></section>
    <section className="bg-white px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-7 lg:grid-cols-3"><InfoList icon={Hammer} title="Practical work" items={programme.projects} /><InfoList icon={BriefcaseBusiness} title="Possible careers" items={programme.careers} /><InfoList icon={GraduationCap} title="Further study" items={programme.furtherStudy} /></div><p className="mt-8 text-sm leading-6 text-slate-500">Career outcomes depend on completed qualifications, experience, further certification, and employer requirements. The programme provides a strong practical and academic foundation for continued growth.</p></div></section>
    <section className="bg-slate-950 px-5 py-16 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="text-xs font-black uppercase tracking-widest text-cyan-300">Continue exploring</p><h2 className="mt-2 text-3xl font-black">Next: {nextProgramme.name}</h2></div><div className="flex flex-wrap gap-3"><Link href={`/programmes/${nextProgramme.slug}`} className="inline-flex min-h-12 items-center gap-2 rounded-full border border-white/25 px-6 font-bold hover:bg-white/10">View programme <ArrowRight className="size-4" /></Link><Link href="/admissions" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-cyan-400 px-6 font-bold text-slate-950 hover:bg-cyan-300">Apply now <ArrowRight className="size-4" /></Link></div></div></section><PublicFooter /></main>;
}

function InfoList({ icon: Icon, title, items }: { icon: typeof CheckCircle2; title: string; items: string[] }) { return <div className="rounded-[1.75rem] border border-slate-200 bg-[#f8fbfb] p-7 shadow-sm"><span className="grid size-12 place-items-center rounded-2xl bg-cyan-100 text-cyan-800"><Icon className="size-6" /></span><h3 className="mt-5 text-xl font-black">{title}</h3><ul className="mt-5 space-y-3">{items.map((item) => <li key={item} className="flex gap-3 text-sm leading-6 text-slate-600"><CheckCircle2 className="mt-1 size-4 shrink-0 text-cyan-600" />{item}</li>)}</ul></div>; }
